[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=42", "wheel"]

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
atomic = true
case_sensitive = true
combine_as_imports = true
line_length = 88
skip_gitignore = true
