---
name: Python unit tests

on:
  pull_request:
    branches:
      - "**"
    tags-ignore:
      - "**"
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"

jobs:
  Test:
    runs-on: ubuntu-latest

    env:
      PY_COLORS: "1"

    strategy:
      matrix:
        include:
          # Django 4.1
          - {tox_env: "py3-django41", python: "3.11"}
          - {tox_env: "py3-django41", python: "3.10"}
          - {tox_env: "py3-django41", python: "3.9"}
          - {tox_env: "py3-django41", python: "3.8"}

          # Django 4.0
          - {tox_env: "py3-django40", python: "3.10"}
          - {tox_env: "py3-django40", python: "3.9"}
          - {tox_env: "py3-django40", python: "3.8"}
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install `tox`
        run: python3 -m pip install tox

      - name: Run unit tests
        run: python3 -m tox -e ${{ matrix.tox_env }} -- --randomly-seed ${{ github.run_number }}
