---
name: End-to-end tests

on: workflow_dispatch

concurrency: end_to_end_testing_environment

jobs:
  Test:
    continue-on-error: true
    environment: end_to_end_testing_environment
    runs-on: ubuntu-latest
    timeout-minutes: 60

    env:
      PY_COLORS: "1"

    strategy:
      max-parallel: 3
      matrix:
        capabilities:
          # Desktop browsers
          - platform: "WIN10"
            browserName: "chrome"
            version: "latest"
          - platform: "WIN10"
            browserName: "edge"
            version: "latest"
          - platform: "WIN10"
            browserName: "firefox"
            version: "latest"
          - platform: "WIN10"
            browserName: "opera"
            version: "latest"
          - platform: "VENTURA"
            browserName: "safari"
            version: "latest"

    steps:
      - name: Check-out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install `tox`
        run: python3 -m pip install tox

      - name: Generate unique TestingBot Tunnel ID
        run: >
          echo "TESTINGBOT_TUNNEL_ID=TB-$(cat /proc/sys/kernel/random/uuid)" >>
          $GITHUB_ENV

      - name: Set up TestingBot Tunnel
        uses: testingbot/testingbot-tunnel-action@v1.1.0
        with:
          key: "${{ secrets.TESTINGBOT_KEY }}"
          secret: "${{ secrets.TESTINGBOT_SECRET }}"
          tunnelIdentifier: "${{ env.TESTINGBOT_TUNNEL_ID }}"

      - name: Dump target capabilities to JSON file
        run: >
          echo '{"capabilities": ${{ toJSON(matrix.capabilities) }}}' >>
          ${{ runner.temp }}/capabilities.json

      - name: Run end-to-end tests
        run: >
          python3 -m tox -e py3-end2end --
          --driver TestingBot
          --capability tunnel-identifier "${{ env.TESTINGBOT_TUNNEL_ID }}"
          --capability selenium-host "http://localhost"
          --capability selenium-port "4445"
          --capability build "End-to-end tests #${{ github.run_number }}"
          --capability public "true"
          --variables "${{ runner.temp }}/capabilities.json"
        env:
          TESTINGBOT_KEY: "${{ secrets.TESTINGBOT_KEY }}"
          TESTINGBOT_SECRET: "${{ secrets.TESTINGBOT_SECRET }}"
